import type { Metadata } from "next";
import { generalSansFont } from "@/styles/fonts";
import "@/styles/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSansFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
