import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/global.css";

import Footer from "./_components/Footer";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const generalSansFont = localFont({
  src: [
    {
      path: "../assets/fonts/GeneralSans-Variable.woff2",
      style: "normal",
    },
    {
      path: "../assets/fonts/GeneralSans-VariableItalic.woff2",
      style: "italic",
    },
  ],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSansFont.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
